# Generated by Django 4.2 on 2023-05-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
